language: node_js

node_js:
  - "12"
  - "10"
  - "8"

# before_install:
#   - curl -L https://unpkg.com/@pnpm/self-installer | node
# install:
#   - pnpm install

script:
  - npm run lint-ci
  - npm run test-ci

notifications:
  email:
    on_success: never
    on_failure: always
